### ISSUE TITLE
Share the Contracts defined in TS to the view layer

### ISSUE THREAD

**Issue by nicktaras** [SmartTokenLabs/tokenscript-engine#14]
To improve the flexibility of TS we should share via the data entry object the contracts defined in the TS.

The use case for this is when you are managing several contracts inside the JS and wish to read data from them.
When working between main/test nets it will prove useful and mean that there is only one source of truth for the definition required per project.

**Comment by micwallace** [comment]
@nicktaras This has been implemented. You can also get a ethers.js contract instance using the ABI specified in the XML:

https://sln-doc.vercel.app/framework/card-sdk/ethereum-methods#getcontractinstance

This eliminates the need to hardcode contract addresses in Javascript.

Note: The provider cannot be used for transactions at this time.
