### ISSUE TITLE
Idea: Align Popular token list with Launch Pad supported tokens

### ISSUE THREAD

**Issue by nicktaras** [SmartTokenLabs/tokenscript-engine#38]
Idea: Align Popular token list with Launch Pad supported tokens

**Comment by nicktaras** [comment]
<img width="1653" alt="Screenshot 2024-08-21 at 12 49 17 PM" src="https://github.com/user-attachments/assets/e4e4365e-ab12-483a-9cda-7bc8cc9629e7">

**Comment by micwallace** [comment]
@nicktaras I think this has already been done by you right?

**Comment by nicktaras** [comment]
Yep, let's close it.
