### ISSUE TITLE
TokenScript Viewer showing ERC-20 owner balances of 1 to wallets that hold no tokens

### ISSUE THREAD

**Issue by nicktaras** [SmartTokenLabs/tokenscript-engine#44]
<img width="1099" alt="Screenshot 2024-09-16 at 11 01 04 AM" src="https://github.com/user-attachments/assets/a2d3fb4b-7e87-4a2a-b1fb-302915827308">

To replicate:

- Create a new wallet / or connect with an existing that holds no ERC-20s tokens of the TS enabled TS's e.g. PEPE, LINK, SLN.
- View the home screen to see that balances are shown as 1 and the user can view the TS

Expectation:

- Balances to be correct
- User cannot navigate to TS if they have no balance

**Comment by nicktaras** [comment]
example of ERC-721 

<img width="1092" alt="Screenshot 2024-09-16 at 11 11 34 AM" src="https://github.com/user-attachments/assets/8f0d41ee-6380-4791-b430-2b45358a8646">
<img width="278" alt="Screenshot 2024-09-16 at 11 11 29 AM" src="https://github.com/user-attachments/assets/ee39adbc-1732-43fd-9ba6-29e083397c0c">

**Comment by micwallace** [comment]
Resolved. The tokenscript tile will now show exact balance rather than number of distinct tokens for tokenscripts with a single token origin
