### ISSUE TITLE
Feed Cat via T-Link

### ISSUE THREAD

**Issue by nicktaras** [SmartTokenLabs/tokenscript-engine#47]
Using T-Link via Twitter there are 38 pending MetaMask events when using another wallet to make the TX to feed the cat. 

I’ve placed this issue in this repo, where it’s looks to be caused by the TS engine itself - from attempting transactions as a non-owner of the token. 

cc: @zhangzhongnan928

**Comment by micwallace** [comment]
@nicktaras Seems like the RPC error isn't being correctly forwarded back to the engine. It should say that the user is not the cat owner. I'm guessing you receive "Internal JSON-RPC error." too?

**Comment by zhangzhongnan928** [comment]
> @nicktaras Seems like the RPC error isn't being correctly forwarded back to the engine. It should say that the user is not the cat owner. I'm guessing you receive "Internal JSON-RPC error." too?

https://x.com/TantanFu122765/status/1844177981943758888 This one

**Comment by futantan** [comment]
![CleanShot 2024-10-15 at 19 17 43@2x](https://github.com/user-attachments/assets/1389ea63-8c42-4d2e-ab2d-bbf0402c174a)

I tried with another wallet, it looks good on my side.
hi @zhangzhongnan928 @micwallace are you able to reproduce this?

**Comment by zhangzhongnan928** [comment]
https://x.com/TantanFu122765/status/1835822673571762177 
I clicked mint button, and it created 26 TX in metamsk
<img width="526" alt="Screenshot 2024-10-15 at 7 40 19 pm" src="https://github.com/user-attachments/assets/cfa9f400-b716-451e-9b8c-08d0ffed0260">
<img width="558" alt="Screenshot 2024-10-15 at 7 43 39 pm" src="https://github.com/user-attachments/assets/1cb0380b-2d90-4cd7-b991-5d7bfefb953c">

**Comment by futantan** [comment]
https://github.com/user-attachments/assets/2d9bc9e6-7391-4daf-821f-5ec4800d0cf0

works on my side... 🤔

**Comment by zhangzhongnan928** [comment]
Does it because I’m not the tapp owner?

**Comment by zhangzhongnan928** [comment]
https://github.com/user-attachments/assets/1ff1b1b8-091d-48fb-8bd7-a583ad2b83bf

**Comment by micwallace** [comment]
@zhangzhongnan928 what is the Twitter post URL?

**Comment by micwallace** [comment]
@zhangzhongnan928 @futantan DW I think I know the problem, will investigate further tomorrow.

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928 what is the Twitter post URL?

https://x.com/TantanFu122765/status/1835822673571762177

**Comment by micwallace** [comment]
@zhangzhongnan928 @futantan Oddly I'm not seeing the problem and was able to mint a token successfully. There were no other transaction requests.

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928 @futantan Oddly I'm not seeing the problem and was able to mint a token successfully. There were no other transaction requests.

But I got same TX repeat 10+ times.

**Comment by micwallace** [comment]
@zhangzhongnan928 I've added a commit to fix the issue in the TLink extension, so it will be resolved next time @futantan does a release.
